apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-api
  labels:
    tier: backend
    app: restaurant-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restaurant-api
  template:
    metadata:
      labels:
        app: restaurant-api
    spec:
      containers:
        - name: restaurant-api-container
          image: bishal12/restaurant-api:staging
          resources:
            requests:
              cpu: "250m"
              memory: "2Gi"
            limits:
              cpu: "500m"
              memory: "5Gi"
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1


        