apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-demo
  labels:
    app: restaurant-demo-web
    tiers: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-demo-app
  template:
    metadata:
      labels:
        app: restaurant-demo-app
    spec:
      containers:
        - name: restaurant-demo-container
          image: bishal12/restauarnt-demo:staging
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
    
